### ISSUE TITLE
Indentation is all over the place...

### ISSUE THREAD

**Issue by ssteinerx** [JSSolutions/get-it-done#2]
It looks like some files are indented with tabs which show up as 8 character indents on Github.

So, some files show 2 character indents, some show 8...that's why indenting with spaces has become the norm.

S

**Comment by ssteinerx** [comment]
https://www.dropbox.com/s/1fa6td8ld5xfl28/Screenshot%202015-08-06%2008.36.28.png?dl=0

**Comment by eterey** [comment]
Thanks. Done.
